#!/usr/bin/env python3
"""MojoLlama JIT Compiler — generates dimension-specific Mojo worker binaries.

Each model gets a compiled Mojo binary with hardcoded dimensions, avoiding
the Int(PythonObject) and unsafe_from_address Mojo 1.0.0b1 limitations.

Usage:
  python3 jit_compile.py <model.gguf>
  
Output: /dev/shm/mojollama_q4_worker_<hash>.bin
  The worker reads a .npy weight file and .npy input, writes .npy output.
  It's called as: <worker> <weights.npy> <input.npy> <output.npy> <start_row> <end_row>
"""

import os
import sys
import json
import hashlib
import subprocess
import importlib.util
import numpy as np

# ─── Template ────────────────────────────────────────────────────────

WORKER_TEMPLATE = '''\
"""MojoLlama Q4_0 worker ({model_desc})
Generated by jit_compile.py — do not edit.
Dimensions: n_embd={N_EMBD}, n_ff={N_FF}, n_layers={N_LAYERS}
"""
from python import Python
from std.memory.unsafe_pointer import alloc

alias F32x8 = SIMD[DType.float32, 8]
alias U8x16 = SIMD[DType.uint8, 16]

alias N_COLS = {N_COLS}
alias N_ROWS = {N_ROWS}
alias BPR = {N_COLS} // 32
alias W_BYTES = {N_ROWS} * BPR * 18

# ─── Dequantize one f16 scale ────────────────────────────────────────

def f16_to_f32(h: UInt16) -> Float32:
    from std.sys.info import CompilationTarget
    from std.memory import bitcast
    comptime if CompilationTarget.has_avx2():
        return Float32(bitcast[DType.float16](h))
    else:
        var s = (UInt32(h) >> 15) & 1
        var e = (UInt32(h) >> 10) & 0x1f
        var m = UInt32(h) & 0x3ff
        if e == 0:
            if m == 0: return Float32(bitcast[DType.float32](s << 31))
            var mm = m; var c: UInt32 = 0
            while mm > 0: mm >>= 1; c += 1
            var sh = 24 - c
            return Float32(bitcast[DType.float32]((s << 31) | ((UInt32(113 - sh)) << 23) | ((m << (sh + 13)) & 0x7fffff)))
        if e == 31: return Float32(bitcast[DType.float32]((s << 31) | 0x7f800000 | (m << 13)))
        return Float32(bitcast[DType.float32]((s << 31) | ((e + 112) << 23) | (m << 13))))

# ─── Q4_0 block dot product (GGUF v2/v3: low nibbles first) ─────────

def q4_block_dot(scale: Float32, nibbles: U8x16, x0: F32x8, x1: F32x8, x2: F32x8, x3: F32x8) -> Float32:
    # Low nibbles = positions 0-15, high nibbles = positions 16-31
    @parameter
    def dg(s: Int, xv: F32x8) -> Float32:
        var v = F32x8()
        for j in range(4):
            var b_low = nibbles[s + j]
            v[j * 2] = Float32(Int8(b_low & 15) - 8)
            v[j * 2 + 1] = Float32(Int8(((b_low >> 4) & 15)) - 8)
        return (v * scale * xv).reduce_add()
    return dg(0, x0) + dg(4, x1) + dg(8, x2) + dg(12, x3)

# ─── Blocked Q4_0 matmul (input stays in L1 cache) ───────────────────

def q4_matmul_blocked(
    w: UnsafePointer[mut=False, type=UInt8, origin=_],
    inp: UnsafePointer[mut=False, type=Float32, origin=_],
    out: UnsafePointer[mut=True, type=Float32, origin=_],
    start_row: Int, end_row: Int,
):
    """For each block, compute dot with all rows' sub-blocks.
    This is cache-optimal: 32 input floats (128 B) stay in L1 while
    processing all rows' weight blocks.
    """
    for blk in range(BPR):
        var inp_off = blk * 32
        var x0 = inp.load[width=8](inp_off)
        var x1 = inp.load[width=8](inp_off + 8)
        var x2 = inp.load[width=8](inp_off + 16)
        var x3 = inp.load[width=8](inp_off + 24)
        
        for row in range(start_row, end_row):
            var off = (row * BPR + blk) * 18
            var lo = w.load(off)
            var hi = w.load(off + 1)
            var scale = f16_to_f32((UInt16(hi) << 8) | UInt16(lo))
            var nibs = w.load[width=16](off + 2)
            var dot = q4_block_dot(scale, nibs, x0, x1, x2, x3)
            out.store(row - start_row, out.load(row - start_row) + dot)

# ─── Main: read .npy files, compute, write .npy result ─────────────

def main() raises:
    var np = Python.import_module("numpy")
    var sys = Python.import_module("sys")
    var bltns = Python.import_module("builtins")
    
    var argv = sys.argv
    var argc = bltns.len(argv)
    if argc < 6:
        print("Usage: worker <weights.npy> <input.npy> <output.npy> <start_row> <end_row>", file=sys.stderr)
        sys.exit(1)
    
    # Read weights
    var w_np = np.load(str(argv[1]))
    var inp_np = np.load(str(argv[2]))
    var out_path = str(argv[3])
    var start_row = {START_ROW}
    var end_row = {END_ROW}
    var n_chunk = end_row - start_row
    
    # Copy weights to Mojo heap
    var w_buf = alloc[UInt8](W_BYTES)
    for i in range(W_BYTES):
        w_buf.store(i, UInt8(w_np.flatten()[i]))
    
    # Copy input to Mojo heap
    var inp_buf = alloc[Float32](N_COLS)
    for i in range(N_COLS):
        inp_buf.store(i, Float32(inp_np.flatten()[i]))
    
    # Result buffer
    var out_buf = alloc[Float32](n_chunk)
    for i in range(n_chunk):
        out_buf.store(i, Float32(0.0))
    
    # Compute
    q4_matmul_blocked(w_buf, inp_buf, out_buf, start_row, end_row)
    
    # Write result
    var out_list = Python.evaluate("[]")
    for i in range(n_chunk):
        Python.evaluate("out_list.append").__call__(out_buf.load(i))
    var out_np = np.array(out_list, dtype=np.float32)
    np.save(out_path, out_np)
    
    w_buf.free()
    inp_buf.free()
    out_buf.free()
'''


def generate_worker_code(n_rows: int, n_cols: int, model_desc: str = "") -> str:
    """Generate Mojo source code with hardcoded dimensions.
    
    The variable dimensions are n_rows and n_cols. For a specific model
    like Llama 3.2 1B:
      - attn Q/O weight: n_embd × n_embd (2048×2048)
      - attn K/V: n_embd × n_kv_head*head_dim (2048×512)
      - FFN gate/up: n_ff × n_embd (8192×2048)
      - FFN down: n_embd × n_ff (2048×8192)
    """
    return WORKER_TEMPLATE.format(
        N_ROWS=n_rows,
        N_COLS=n_cols,
        BPR=n_cols // 32,
        N_EMBD=n_cols,
        N_FF=n_rows if n_rows > n_cols else n_cols * 4,
        N_LAYERS="??",
        START_ROW=0,
        END_ROW=n_rows,
        model_desc=model_desc or f"{n_rows}x{n_cols}",
    )


def generate_all_workers(n_embd: int, n_ff: int, n_kv: int) -> dict:
    """Generate worker source for all matmul shapes in a model."""
    workers = {}
    workers['q'] = generate_worker_code(n_embd, n_embd, f"Q attention {n_embd}x{n_embd}")
    workers['k'] = generate_worker_code(n_kv, n_embd, f"K attention {n_kv}x{n_embd}")
    workers['v'] = generate_worker_code(n_kv, n_embd, f"V attention {n_kv}x{n_embd}")
    workers['o'] = generate_worker_code(n_embd, n_embd, f"O attn_proj {n_embd}x{n_embd}")
    workers['gate'] = generate_worker_code(n_ff, n_embd, f"FFN gate {n_ff}x{n_embd}")
    workers['up'] = generate_worker_code(n_ff, n_embd, f"FFN up {n_ff}x{n_embd}")
    workers['down'] = generate_worker_code(n_embd, n_ff, f"FFN down {n_embd}x{n_ff}")
    return workers


def compile_worker(source_path: str, output_path: str) -> bool:
    """Compile a Mojo source file to a binary."""
    result = subprocess.run(
        ["mojo", "build", source_path, "-o", output_path],
        capture_output=True, text=True, timeout=60
    )
    if result.returncode != 0:
        print(f"  ❌ Compile error: {result.stderr[:300]}")
        return False
    return True


def jit_compile_model(gguf_path: str, force=False) -> dict:
    """Read GGUF, compile all 7 worker shapes, return worker info."""
    import gguf
    from gguf.constants import GGMLQuantizationType
    
    reader = gguf.GGUFReader(gguf_path)
    f = reader.get_field
    arch = str(f('general.architecture').parts[-1]) if f('general.architecture') else 'unknown'
    prefix = f'{arch}.'
    
    n_embd = int(f(f'{prefix}embedding_length').parts[-1].item())
    n_head = int(f(f'{prefix}attention.head_count').parts[-1].item())
    n_kv_head = int(f(f'{prefix}attention.head_count_kv').parts[-1].item())
    n_ff = int(f(f'{prefix}feed_forward_length').parts[-1].item())
    n_layers = int(f(f'{prefix}block_count').parts[-1].item())
    head_dim = n_embd // n_head
    n_kv = n_kv_head * head_dim
    
    print(f"Model: {gguf_path}")
    print(f"  Arch: {arch}, {n_layers} layers")
    print(f"  n_embd={n_embd}, n_head={n_head}, n_kv_head={n_kv_head}")
    print(f"  head_dim={head_dim}, n_ff={n_ff}, n_kv={n_kv}")
    print()
    
    # Generate worker source
    workers_info = {
        'q': (n_embd, n_embd),
        'k': (n_kv, n_embd),
        'v': (n_kv, n_embd),
        'o': (n_embd, n_embd),
        'gate': (n_ff, n_embd),
        'up': (n_ff, n_embd),
        'down': (n_embd, n_ff),
    }
    
    compiled = {}
    model_hash = hashlib.md5(gguf_path.encode()).hexdigest()[:8]
    
    for name, (n_rows, n_cols) in workers_info.items():
        src_path = f"/dev/shm/mojo_worker_{model_hash}_{name}.mojo"
        bin_path = f"/dev/shm/mojo_worker_{model_hash}_{name}.bin"
        
        if os.path.exists(bin_path) and not force:
            compiled[name] = bin_path
            continue
        
        code = generate_worker_code(n_rows, n_cols, f"{name} {n_rows}x{n_cols}")
        with open(src_path, 'w') as f:
            f.write(code)
        
        print(f"  Compiling {name} ({n_rows}x{n_cols})... ", end="")
        ok = compile_worker(src_path, bin_path)
        print("✅" if ok else "❌")
        if ok:
            compiled[name] = bin_path
    
    return {
        "workers": compiled,
        "model_hash": model_hash,
        "n_embd": n_embd,
        "n_ff": n_ff,
        "n_kv": n_kv,
        "n_layers": n_layers,
    }


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 jit_compile.py <model.gguf>")
        sys.exit(1)
    
    info = jit_compile_model(sys.argv[1])
    print()
    print(f"Compiled {len(info['workers'])} worker binaries:")
    for name, path in info['workers'].items():
        size = os.path.getsize(path)
        print(f"  {name}: {path} ({size//1024} KB)")
